metadata1/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Office_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Office Manager lookup populated via Process Builder flow &apos;Office Manager Population onto Account&apos; used in Account Creation Approval Process</description>
        <label>Office Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Office Manager)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata1/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account does not exist or has been rejected.</errorMessage>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ATI Jobs</relationshipLabel>
        <relationshipName>ATI_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <description>Date that the Job&apos;s Stage is set to Complete</description>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to link the primary Contact of the Job to the Opportunity</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Contact)</relationshipLabel>
        <relationshipName>ATIContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date_Per_PD__c</fullName>
        <label>Estimated Completion Date Per PM</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>This date should reflect the estimated completion date on the contract with the customer.</description>
        <label>Estimated Completion Date per Contract</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurance_Adjuster_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Insurance Adjuster/Broker for this Job-- referenced in New Job VF page</description>
        <label>Insurance Adjuster/Broker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Insurance Adjuster/Broker)</relationshipLabel>
        <relationshipName>ATIJobIAB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising and Publications</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Building Consultant</fullName>
                </value>
                <value>
                    <fullName>Consulting Firm</fullName>
                </value>
                <value>
                    <fullName>Employee - Friends or Family Referral</fullName>
                </value>
                <value>
                    <fullName>Environmental Hygienist</fullName>
                </value>
                <value>
                    <fullName>Facilities Management/Building Engineer</fullName>
                </value>
                <value>
                    <fullName>General Contractor</fullName>
                </value>
                <value>
                    <fullName>Government or Municipality</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Independent Adjusting Company</fullName>
                </value>
                <value>
                    <fullName>Insurance Agent</fullName>
                </value>
                <value>
                    <fullName>Insurance Broker</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Live Chat</fullName>
                </value>
                <value>
                    <fullName>National Account (ERA, Contract, Etc)</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity Consumer Services</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity REO</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity Services</fullName>
                </value>
                <value>
                    <fullName>Program - American Emergency Services</fullName>
                </value>
                <value>
                    <fullName>Program - ASI Claims</fullName>
                </value>
                <value>
                    <fullName>Program - BrightServ</fullName>
                </value>
                <value>
                    <fullName>Program - CC Consumer Services</fullName>
                </value>
                <value>
                    <fullName>Program - Code Blue Network</fullName>
                </value>
                <value>
                    <fullName>Program - Contractor Connection</fullName>
                </value>
                <value>
                    <fullName>Program - Direct Assignment</fullName>
                </value>
                <value>
                    <fullName>Program - Direct Claims Management (DCMG)</fullName>
                </value>
                <value>
                    <fullName>Program - IMACC</fullName>
                </value>
                <value>
                    <fullName>Program - Innovation Property</fullName>
                </value>
                <value>
                    <fullName>Program - Lionsbridge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Office object to indicate what office the Job is taking place out of.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>ATIOffice2</relationshipLabel>
        <relationshipName>ATIOffice2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Field to indicate the ATI office associated with the job.
(Hidden Field) Only for Apex Triggers Code and other reports not for UI.</description>
        <formula>Office2__r.Name</formula>
        <label>Office Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent_Complete__c</fullName>
        <label>Percent Complete</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Manager assigned to this job</description>
        <label>Project Director</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Executive Management, Project Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobpm1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager_new__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will up updated via process builder depending on the Ops manager and/or Superintendent.</description>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIProjectManagerNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Billing_Forecast_Amount__c</fullName>
        <label>Total Billing Forecast Amount</label>
        <summarizedField>Forecast__c.Revenue_Amount__c</summarizedField>
        <summaryForeignKey>Forecast__c.ATI_Job__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata1/unpackaged/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>ATI_Job__c</fullName>
        <label>Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <formula>ATI_Job__r.Estimated_Completion_Date__c</formula>
        <inlineHelpText>To edit the date, please refer back to ATI Job.</inlineHelpText>
        <label>Estimated Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets_PM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets_RegMgr</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata1/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ATI_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ATI Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

metadata1/unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Flagstaff</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Anaheim</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Pittsburgh</fullName>
                </value>
                <value>
                    <fullName>Riverside</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>San Jose</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tuscon</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata1/unpackaged/objects/Office__c.object
<CustomObject>
    <fields>
        <fullName>Office_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OfficesdlDf</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Admin_two__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Admin 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OfficesE1CT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Offices80Iv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Manager (DEL)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OfficesdlDL</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JobButtons.cls
/**
 * @File Name          : JobButtons.cls
 * @Description        : 
 * @Author             : Sean Gray
 * @Group              : 
 * @Last Modified By   : Sean Gray
 * @Last Modified On   : 2/2/2020, 3:03:59 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/1/2020   Sean Gray     Initial Version
**/
public with sharing class JobButtons {
    @AuraEnabled
    public static Date projectNoteDate(String recordId){
         if(recordId != null){
        List<ATI_Job__c> job = [Select Id, Estimated_Completion_Date_Per_PD__c FROM ATI_Job__c WHERE Id =: recordId];
        system.debug('Job info is : '+' Job Info 0 is : ' + job);
       
        return job[0].Estimated_Completion_Date_Per_PD__c;
        }else{
            return null;
        }
    }
     @AuraEnabled
     public static Decimal projectNotePercent(String recordId){
         if(recordId != null){
        List<ATI_Job__c> job = [Select Id, Percent_Complete__c FROM ATI_Job__c WHERE Id =: recordId];

       
        return job[0].Percent_Complete__c;
        }else{
            return null;
        }
    }
    @AuraEnabled
    public static String createTaskProjectNote(Decimal percent, String recordId, String ownerId, String workCompleted, String workStarted, Date completionDate, String insured, String supplement, String repairComments){
        ATI_Job__c job = [Select Id, office2__c, Project_Manager__c, Project_manager_new__c, lead_source__c, Name, Percent_Complete__c, Estimated_Completion_Date_Per_PD__c FROM ATI_Job__c WHERE Id =: recordId];
        List<office__c> office = [Select Id, office_manager__c, project_coordinator__c, project_admin_two__c FROM Office__c WHERE id =:job.office2__c];
        system.debug('Working + ' + ownerId);
        string comments = '\n' + 'Project Note: ' + job.name +'\n' + '\n' + '\n' + 'Percent of Job Complete: ' + percent + '%' + '\n' +'\n' + 'Work/Trades started/completed since last week: ' + workCompleted + '\n' +'\n' + 'Work to be started this week: '+ workStarted + '\n' + '\n' +'Estimated completion date Per PM: '+ completionDate + '\n' + '\n' +'Has Insured/Member completed all selections? Y/N:' + insured + '\n' +'\n' + 'Potential Supplement?Y/N: '+ supplement + '\n' +'\n' + 'Repair Update Comments: ' + repairComments;
        Task t = new Task( Type = 'Project Note', ActivityDate = system.today(), Description = comments, OwnerId = ownerId, Priority = 'Low', Status='Completed', Subject = 'Project Note', WhatId = recordId);
        
        insert t;
        system.debug('Task '+ t);
        FeedItem post = new FeedItem();
        post.ParentId = recordId;
        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
        ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
        messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
        ConnectApi.MentionSegmentInput mentionSegmentInput1 = new ConnectApi.MentionSegmentInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput2 = new ConnectApi.MentionSegmentInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput3 = new ConnectApi.MentionSegmentInput();
        if(job.lead_source__c.startsWith('Program') && office != null && office[0].project_admin_two__c != null){
        mentionSegmentInput3.id = office[0].project_admin_two__c;
        messageBodyInput.messageSegments.add(mentionSegmentInput3);
        }
        if(job.Project_Manager__c != null){
        mentionSegmentInput.id = job.project_manager__c;
        messageBodyInput.messageSegments.add(mentionSegmentInput);
        }
        if(job.Project_Manager_new__c != null){
            mentionSegmentInput1.id = job.project_manager_new__c;
             messageBodyInput.messageSegments.add(mentionSegmentInput1);
        }
        if(job.lead_source__c.startsWith('Program') && office != null && office[0].project_coordinator__c != null){
             mentionSegmentInput2.id = office[0].project_coordinator__c;
            messageBodyInput.messageSegments.add(mentionSegmentInput2);
        }
       
        
        //messageBodyInput.messageSegments.add(mentionSegmentInput1);
        
        textSegmentInput.text = comments;
        messageBodyInput.messageSegments.add(textSegmentInput);
        feedItemInput.body = messageBodyInput;
        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
        feedItemInput.subjectId = recordId;
        if(Test.isRunningTest()){return 'success';}
        else{
        ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput);
        UpdateProjectNote(job.id, completionDate, percent);
        // job.Percent_Complete__c = percent;
        // job.Estimated_Completion_Date_Per_PD__c = completionDate;
        // update job;
        return 'Success';
        }
//insert feedElement;

       
    }
    
    @future
    public static void UpdateProjectNote(Id JobID, Date estimatedCompletionDate, Decimal percent){
        ATI_Job__c job = new ATI_Job__c(ID = JobID, Estimated_completion_date_per_PD__c = estimatedCompletionDate, percent_complete__c = percent);
        update job;
    }

    @AuraEnabled
    public static string PMAssignmentQuery(String recordId){
        
        ATI_Job__c job = [Select Id, Account__r.Name, lead_source__c, amount__c,total_billing_forecast_amount__c, Insurance_Adjuster_Broker__c, contact__c,office2__c, Project_Manager__c, Project_manager_new__c, Name, Percent_Complete__c, Estimated_Completion_Date__c, completion_date__c FROM ATI_Job__c WHERE Id =: recordId];
        List<office__c> office = [Select Id, office_manager__c, project_coordinator__c, regional_manager__c FROM Office__c WHERE id =:job.office2__c];
        //List<Contact> cont = [Select Name FROM Contact Where Id =: job.contact__c];
        // Contact ins = new Contact();
        // if(job.Insurance_Adjuster_Broker__c != null){
        // ins = [Select Name FROM Contact Where Id =: job.Insurance_Adjuster_Broker__c Limit 1];
        // }
        List<Budget__c> bud = new List<Budget__c>();
        bud = [Select Name, Total_Allocations__c, Total_Program_Fees_New__c, Total_Budget_Goal__c, ATI_Job__c FROM Budget__c Where ATI_Job__c =:job.id Order By createdDate DESC Limit 1];
        Budget__c bu = new Budget__c();
        for(budget__c b : bud){
            bu = b;
        }
        String PMAssignmentResults;
        // if(!ins.isEmpty()){
        PMAssignmentResults = '{"Insurance":"'+ job.Account__r.Name + ' ' + job.lead_source__c +'", "Fees":"'+bu.Total_Program_Fees_New__c+'","Allocation":"'+ bu.Total_Allocations__c +'", "Price":"'+ job.amount__c +'", "Budget":"'+ bu.Total_Budget_Goal__c +'", "Forecast":"'+ job.total_billing_forecast_Amount__c +'"}';  
        // }else{
        // PMAssignmentResults = '{"Insurance":"'+ 'Null' +'", "Fees":"'+bud[0].Total_Program_Fees_New__c+'","Allocation":"'+ bud[0].Total_Allocations__c +'", "Price":"'+ job.amount__c +'", "Budget":"'+ bud[0].Total_Budget_Goal__c +'", "Forecast":"'+ job.total_billing_forecast_Amount__c +'"}';
        // }
            system.debug('JSON set up : ' + PMAssignmentResults);
            return PMAssignmentResults;
    }

    public class JSONWrapper{
        public List<Id> ContactString {get;set;}
        public List<Id> ProjectManagerString {get;set;}
    }
    @AuraEnabled
    public static string PMAssignmentChatter(Date startDate, String recordId, String ownerId, Date completionDate,  String notes, String briefScope,String PackagedJSON){
        system.debug('StartDate ' + startDate + ' Record Id ' + recordId);
        JSONWrapper ContactID;
        Id conId;
        Id projectManagerId;
        system.debug('JSON is ' + PackagedJSON);
        ContactID = (JSONWrapper)JSON.deserialize(PackagedJSON, JSONWrapper.class);
        for(Id ca : ContactID.ContactString){
        conId = ca;
        }
        for(Id ca1 : ContactID.ProjectManagerString){
        projectManagerId = ca1;
        }
         Contact contactName = new Contact();
         contactName = [Select Name, mobilephone FROM Contact Where Id =: conId];
        User pm = [Select Name FROM User WHere Id =: projectManagerId];
         
        ATI_Job__c job = [Select Id, amount__c,total_billing_forecast_amount__c,Account__r.Name, Lead_Source__c, contact__c,office2__c, Project_Manager__c, Project_manager_new__c, Name, Percent_Complete__c, Estimated_Completion_Date_Per_PD__c, completion_date__c FROM ATI_Job__c WHERE Id =: recordId];
        List<office__c> office = [Select Id, office_manager__c, project_coordinator__c, branch_manager__c FROM Office__c WHERE id =:job.office2__c];
        //  Contact ins = new Contact();
        //  if(job.Insurance_Adjuster_Broker__c != null){
        // ins = [Select Name FROM Contact Where Id =: job.Insurance_Adjuster_Broker__c];
        //  }
        List<Budget__c> bud = [Select Name, Total_Allocations__c, Total_Program_Fees_New__c, Total_Budget_Goal__c, ATI_Job__c FROM Budget__c Where ATI_Job__c =:job.id Order By createdDate DESC Limit 1];
        system.debug('Working + ' + ownerId);
        Budget__c bu = new Budget__c();
        for(budget__c b : bud){
            bu = b;
        }
        String contactUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/' + conId;
        //if(!bud.isempty()){
        //string comments = '\n' + 'PM Assignment: ' + job.name +'\n' + '\n' + '\n' + 'Insurance Carrier/TPA: ' + ins.name +'\n' + 'Fees: ' + bu.Total_Program_Fees_New__c + '\n' + 'Allocation: '+ bu.Total_Allocations__c + '\n'  +'Price: '+ job.amount__c + '\n'  +'Budget: ' + bu.Total_Budget_Goal__c + '\n' + 'Contract Start Date: '+ startDate + '\n' + 'Contract Completion Date: ' + completionDate + '\n' + 'Forecast: '+ job.total_billing_forecast_Amount__c +'\n' + 'Brief Scope: '+briefScope+'\n' + 'Notes: '+notes +'\n' + 'ContactInfo: '+contactInfo+'\n' + 'Suggested PM: ' + projectManager; 
        string comments = '\n' + 'PM Assignment: ' + job.name +'\n' + '\n' + '\n' + 'Insurance Carrier/TPA: ' + job.Account__r + ' ' + job.lead_source__c  +'\n' + 'Fees: ' + bu.Total_Program_Fees_New__c + '\n' + 'Allocation: '+ bu.Total_Allocations__c + '\n'  +'Price: '+ job.amount__c + '\n'  +'Budget: ' + bu.Total_Budget_Goal__c + '\n' + 'Contract Start Date: '+ startDate + '\n' + 'Contract Completion Date: ' + completionDate + '\n' + 'Forecast: '+ job.total_billing_forecast_Amount__c +'\n' + 'Brief Scope: '+briefScope+'\n' + 'Notes: '+notes +'\n' + 'ContactInfo: '+ contactName.Name +  '\n' + 'Suggested PM: ' + pm.Name;
        
        //Task t = new Task( Type = 'Project Note', ActivityDate = system.today(), Description = comments, OwnerId = ownerId, Priority = 'Low', Status='Completed', Subject = 'Project Note', WhatId = recordId);
        //insert t;
        //system.debug('Task '+ t);
        //FeedItem post = new FeedItem();
        //post.ParentId = recordId;
        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
        ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
        messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
        ConnectApi.MentionSegmentInput mentionSegmentInput1 = new ConnectApi.MentionSegmentInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput2 = new ConnectApi.MentionSegmentInput();
        mentionSegmentInput.id = job.project_manager__c;
        //mentionSegmentInput1.id = job.project_manager_new__c;
        if(office != null && office[0].office_manager__c != null){
             mentionSegmentInput1.id = office[0].office_manager__c;
            messageBodyInput.messageSegments.add(mentionSegmentInput1);
        }
        if(office != null && office[0].branch_manager__c != null){
             mentionSegmentInput2.id = office[0].branch_manager__c;
            messageBodyInput.messageSegments.add(mentionSegmentInput2);
        }
       
        //messageBodyInput.messageSegments.add(mentionSegmentInput);
       // messageBodyInput.messageSegments.add(mentionSegmentInput1);
        
        textSegmentInput.text = comments;
        messageBodyInput.messageSegments.add(textSegmentInput);
        feedItemInput.body = messageBodyInput;
        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
        feedItemInput.subjectId = recordId;
        ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput);
        //job.estimated_completion_date_per_PD__c = completionDate;
        UpdateCompletionDatePerPM(job.id, completionDate, projectManagerId);
       //update job;
//insert feedElement;
        approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval. Details are: ' + comments);
        req1.setObjectId(recordId);
        // Submit on behalf of a specific submitter
        req1.setSubmitterId(UserInfo.getUserId());
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('PMAssignmentApproval');
        req1.setSkipEntryCriteria(true);
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);

        return 'Success';
    }
    @future
    public static void UpdateCompletionDatePerPM(Id JobID, Date completionDatePerPD, Id ProjectManagerId){
        ATI_Job__c job = new ATI_Job__c(ID = JobID, Estimated_Completion_Date__c = completionDatePerPD, Suggested_PM__c = ProjectManagerId, PM_Assignment_Status__c = 'Sent for Approval');
        update job;
    }


    @AuraEnabled
    public static string JobCaseInfo(Id recordId){
    ATI_Job__c job = [Select Id, project_site_contact_name__c FROM ATI_Job__c Where Id =: recordId];
    if(job.project_Site_contact_name__c != null){
    return job.project_site_contact_Name__c;
    }else{
        return null;
    }
    }
    @AuraEnabled
    public static string ContactAccount(Id recordId){
    ATI_Job__c job = [Select Id, project_site_contact_name__c FROM ATI_Job__c Where Id =: recordId];
    
    if(job.project_Site_contact_name__c != null){
        system.debug('Job project site contact ' + job.Project_Site_Contact_Name__c);
        Contact c = [Select id, AccountId FROM Contact where id =: job.Project_Site_Contact_Name__c];
        system.debug('contact is ' + c);
    Account a = [Select Id FROM Account Where Id =: c.AccountId];
    system.debug('Account ' + a);
    return a.id;
    }else{
        return null;
    }
    }
    @AuraEnabled
    public static Case ChatterJobId(Id recordId) {
        Case cs = [Select Id, ATI_Job__c FROM Case Where Id =: recordId];
        system.debug('Cs is ' + cs);
        return cs;
    }
    @AuraEnabled
    public static String CaseChatterTaskCreation(Id recordId, String subject, String description){
        
            
       
        Id caseOwner = UserInfo.getUserId();
        List<case> cases = [Select Id FROM CASE WHERE ATI_Job__c =: recordId ORDER BY createdDate DESC LIMIT 1];
        system.debug('Cases ' + cases);
        String fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + cases[0].id;
        String fullRecordURLJOB = URL.getSalesforceBaseUrl().toExternalForm() + '/' + recordId;
        
        string descriptionPlus = 'A new case has been opened for the Job: ' + fullRecordURLJOB+  '\n' +'Case Link: '+ fullRecordURL + '\n' + '\n' +description;

        Task t = new Task( Type = 'Log a Call', ActivityDate = system.today(), Description = descriptionPlus, OwnerId = caseOwner, Priority = 'Low', Status='Completed', Subject = subject, WhatId = recordId);
        insert t;
        ATI_Job__c job = [Select Id, Project_Manager__c, Project_manager_new__c, Name FROM ATI_Job__c WHERE Id =: recordId];
        
        FeedItem post = new FeedItem();
        post.ParentId = recordId;
        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
        ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
        messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
        ConnectApi.MentionSegmentInput mentionSegmentInput1 = new ConnectApi.MentionSegmentInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput2 = new ConnectApi.MentionSegmentInput();
        if(job.Project_Manager_new__c != null){
            mentionSegmentInput.id = job.project_manager_new__c;
            messageBodyInput.messageSegments.add(mentionSegmentInput);
        }
        if(job.Project_Manager__c != null){
            mentionSegmentInput1.id = job.project_manager__c;
            messageBodyInput.messageSegments.add(mentionSegmentInput1);
        }
        
        
        String comments = '\n' + 'Case Link: ' + fullRecordURL +  '\n' + '\n' +description;
        // messageBodyInput.messageSegments.add(mentionSegmentInput);
        // messageBodyInput.messageSegments.add(mentionSegmentInput1);
        
        textSegmentInput.text = descriptionPlus;
        messageBodyInput.messageSegments.add(textSegmentInput);
        feedItemInput.body = messageBodyInput;
        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
        feedItemInput.subjectId = recordId;
        if(Test.isRunningTest()){}
        else{
        ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput);
        }
        system.debug('Cases Id before return is ' + cases[0].id);
        return cases[0].id;
        
    }
    @AuraEnabled
    public static string AllocationApproval(String OppName, String recordId, String JobNumber, Integer Amount, String FirstQ, String SecondQ, String ThirdQ, 
    String Subcontractor, String Description){
        system.debug(OppName + recordId + JobNumber + Amount + FirstQ + SecondQ + ThirdQ + Description + Subcontractor);
        approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval. Details are: ');
        req1.setObjectId(recordId);
        // Submit on behalf of a specific submitter
        req1.setSubmitterId(UserInfo.getUserId());
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('X2PercentAllocation');
        req1.setSkipEntryCriteria(true);
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        return 'success';
    }
    
}