metadata1/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account does not exist or has been rejected.</errorMessage>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ATI Jobs</relationshipLabel>
        <relationshipName>ATI_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up field to note the Branch Manager that will need to assign a PM to the job.</description>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobBM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City_of_LA__c</fullName>
        <description>Indicator of whether a Job is located in the city of LA.  Required in New Job VF page.</description>
        <label>City of LA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Information__c</fullName>
        <formula>IF(ISBLANK(Contact__c)=true, &quot;&quot;, 

if(Contact__r.IsPersonAccount = true, (Contact__r.Account.BillingStreet +&quot;, &quot;+ Contact__r.Account.BillingCity +&quot;, &quot;+ Contact__r.Account.BillingState +&quot; &quot;+ Contact__r.Account.BillingPostalCode &amp; BR() &amp; 
Contact__r.Account.Phone +&quot; Work &quot; &amp; BR() &amp; Contact__r.MobilePhone +&quot; Mobile &quot; &amp; BR() &amp; 
Contact__r.Email), 
(Contact__r.MailingStreet +&quot;, &quot;+ Contact__r.MailingCity +&quot;, &quot;+ Contact__r.MailingState +&quot; &quot;+ Contact__r.MailingPostalCode &amp; BR() &amp; 
Contact__r.Phone +&quot; Work &quot; &amp; BR() &amp; Contact__r.MobilePhone +&quot; Mobile &quot; &amp; BR() &amp; 
Contact__r.Email)))</formula>
        <inlineHelpText>Information is carried over from Contact&apos;s Mailing Address.</inlineHelpText>
        <label>Contact Information</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to link the primary Contact of the Job to the Opportunity</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Contact)</relationshipLabel>
        <relationshipName>ATIContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>Job Project Site County-- used in Jitterbit mapping to sync with Timberline.</description>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ATI Jobs (Customer)</relationshipLabel>
        <relationshipName>ATI_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Job_Class__c</fullName>
        <description>Indicator of job classification/industry</description>
        <label>Job Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Multi-Family</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Municipality/ Gov&apos;t</fullName>
                </value>
                <value>
                    <fullName>GSA</fullName>
                </value>
                <value>
                    <fullName>Religious</fullName>
                </value>
                <value>
                    <fullName>Educational - Public</fullName>
                </value>
                <value>
                    <fullName>Educational - Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Job Name field is used on New Job VF page, used to pass along to Timberline, and used to update Opportunity Name field via &apos;Opportunity Naming Convention&apos; workflow.</description>
        <label>Job Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Number__c</fullName>
        <description>Job unique identifier/external ID populated via code.  Numbers are representative of Office, Division, PM ID, and Year.</description>
        <externalId>true</externalId>
        <label>Job Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising and Publications</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Building Consultant</fullName>
                </value>
                <value>
                    <fullName>Consulting Firm</fullName>
                </value>
                <value>
                    <fullName>Employee - Friends or Family Referral</fullName>
                </value>
                <value>
                    <fullName>Environmental Hygienist</fullName>
                </value>
                <value>
                    <fullName>Facilities Management/Building Engineer</fullName>
                </value>
                <value>
                    <fullName>General Contractor</fullName>
                </value>
                <value>
                    <fullName>Government or Municipality</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Independent Adjusting Company</fullName>
                </value>
                <value>
                    <fullName>Insurance Agent</fullName>
                </value>
                <value>
                    <fullName>Insurance Broker</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Live Chat</fullName>
                </value>
                <value>
                    <fullName>National Account (ERA, Contract, Etc)</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity Consumer Services</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity REO</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity Services</fullName>
                </value>
                <value>
                    <fullName>Program - American Emergency Services</fullName>
                </value>
                <value>
                    <fullName>Program - ASI Claims</fullName>
                </value>
                <value>
                    <fullName>Program - BrightServ</fullName>
                </value>
                <value>
                    <fullName>Program - CC Consumer Services</fullName>
                </value>
                <value>
                    <fullName>Program - Code Blue Network</fullName>
                </value>
                <value>
                    <fullName>Program - Contractor Connection</fullName>
                </value>
                <value>
                    <fullName>Program - Direct Assignment</fullName>
                </value>
                <value>
                    <fullName>Program - Direct Claims Management (DCMG)</fullName>
                </value>
                <value>
                    <fullName>Program - IMACC</fullName>
                </value>
                <value>
                    <fullName>Program - Innovation Property</fullName>
                </value>
                <value>
                    <fullName>Program - Lionsbridge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Office object to indicate what office the Job is taking place out of.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>ATIOffice2</relationshipLabel>
        <relationshipName>ATIOffice2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <formula>CASE( Stage__c , &quot;Qualification&quot;, 0.25,&quot;Estimating/Review&quot;, 0.50,&quot;Won&quot;, 1.00,&quot;Work Complete&quot;, 1.00,&quot;Billing Complete&quot;,1.00,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Probability (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Manager assigned to this job</description>
        <label>Project Director</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Executive Management, Project Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobpm1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address_2__c</fullName>
        <label>Project Site Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <description>Address of job project site</description>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field was created to contain information for Project Site Contacts that are Person Account (NOT Contact) records.</description>
        <label>Project Site Contact Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>ATISiteContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project Site Contact Name</description>
        <label>Project Site Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job (Project Site Contact Name)</relationshipLabel>
        <relationshipName>ProjectSiteContactName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <description>Project Type</description>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>Certified</fullName>
                    <label>Prevailing Wage / Certified</label>
                </value>
                <value>
                    <fullName>Union</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact record of the individual that referred ATI to this customer</description>
        <label>Referred by</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referred by)</relationshipLabel>
        <relationshipName>ATIJobRef</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Estimating/Review</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Billing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taken_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Admin responsible for the initial job intake</description>
        <label>Taken By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobTakenBy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CloneATIJob.cls
/**
 * @File Name          : CloneATIJob.cls
 * @Description        : 
 * @Author             : sean.gray@atirestoration.com
 * @Group              : 
 * @Last Modified By   : sean.gray@atirestoration.com
 * @Last Modified On   : 2/17/2020, 11:25:15 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    1/9/2020   sean.gray@atirestoration.com     Initial Version
**/
public class CloneATIJob {
   
   @AuraEnabled
    public static string CloneJobRecord(String recordId, Boolean related){
        ATI_Job__c job = [SELECT Id, name, Job_Name__c,Job_Number__c, Account__c, Contact__c, Customer__c, Lead_Source__c,
                         Description__c, Job_Class__c, Project_Site_Contact_Name__c,Contact_Information__c, Project_Manager__c, 
                         Branch_Manager__c, Project_Site_Contact_Account__c, Office2__c, Stage__c, Taken_By__c, Project_type__c,
                         Referred_by__c, CloseDate__c,Probability__c, County__c, City_of_LA__c, Project_Site_Address_2__c, 
                         Project_site_address__c, Project_site_city__c, Project_site_state__c, Project_site_zipcode__c, Year_Structure_built__c,
                         Date_of_loss__c, Project_Site_Contact_Email__c, no_Email_Available__c, Policy__c, Deductible__c, Claim__c, 
                         Cont_P_O_Client_Job__c, PO__c, Send_prelim__c FROM ATI_Job__c WHERE Id = :recordId];
        string recId;
        if(related){
            recId = recordId;
        }
        else{
            recId = '';
        }
        Id unapprovedRecordTypeId = Schema.SObjectType.ATI_Job__c.getRecordTypeInfosByName().get('New Job (Not Approved)').getRecordTypeId();
        ATI_Job__c newJob = new ATI_Job__c (Name = job.name, recordTypeId = unapprovedRecordTypeId, Job_Name__c = job.Job_Name__c, Job_Number__c= job.Job_Number__c, Account__c = job.Account__c, Contact__c = job.Contact__c,
        Customer__c = job.Customer__c, Lead_Source__c =job.Lead_Source__c, Description__c = job.Description__c, Job_Class__c = job.Job_Class__c, Project_Site_Contact_Name__c = job.Project_Site_Contact_Name__c,  
        Branch_Manager__c = job.Branch_Manager__c, Project_Site_Contact_Account__c = job.Project_Site_Contact_Account__c, Office2__c = job.Office2__c, Stage__c = 'Qualification', Taken_By__c = job.Taken_By__c, Project_type__c = job.Project_type__c,
        Referred_by__c = job.Referred_by__c, CloseDate__c = job.CloseDate__c, County__c = job.County__c, City_of_LA__c = job.City_of_LA__c, Project_Site_Address_2__c = job.Project_Site_Address_2__c, 
        Project_site_address__c = job.Project_site_address__c, Project_site_city__c = job.Project_site_city__c, Project_site_state__c = job.Project_site_state__c, Project_site_zipcode__c = job.Project_site_zipcode__c, Year_Structure_built__c = job.Year_Structure_built__c,
        Date_of_loss__c = job.Date_of_loss__c, no_Email_Available__c = job.no_Email_Available__c, Policy__c = job.Policy__c, Deductible__c = job.Deductible__c, Claim__c = job.Claim__c, 
        Cont_P_O_Client_Job__c = job.Cont_P_O_Client_Job__c, PO__c = job.PO__c, Send_prelim__c = job.Send_prelim__c, Parent_Job__c = recId );
       try {
        insert newJob;
        return newJob.id;
           
       } catch (Exception e) {
           return string.valueOf(e);
       } 
        
        
    } 
}